### ISSUE TITLE
deserializing api response with json.loads not working

### ISSUE THREAD

**Issue by rimmugygur** [intrinio/python-sdk#10]
Expecting to be able to deserialise the api response with "json.loads(api_response)" but getting the error "TypeError: the JSON object must be str, bytes or bytearray, not ApiResponseSecurityStockPrices"

**Comment by zachwick** [comment]
@rimmugygur It appears that all of the various classes defined in the SDK are generated from the OpenAPI spec and include a `to_dict` method that you can use to convert the object retrieved returned by the API into a dictionary (see https://github.com/intrinio/python-sdk/blob/master/intrinio_sdk/models/api_response_security_stock_prices.py#L132 for the `to_dict` method for the `ApiResponseSecurityStockPrices` class).

This means that you don't need to use the json module to deserialize the API response and can instead just make use of the `to_dict` method.

**Comment by rimmugygur** [comment]
Thx, that did the trick
