### ISSUE TITLE
Request: ThrottlingError and other Error types

### ISSUE THREAD

**Issue by RobRoseKnows** [intrinio/python-sdk#6]
So I don't know if this is a limitation of the API or of Swagger but I'm pretty sure I've seen Swagger schemas with custom error types before. It would be useful to have a ThrottlingError that's returned by the API for 429 errors and a ServerError that's returned for 5XX errors. Currently you can get the error code from the error object, but the pythonic way of handling different errors is different `except` clauses.

So while currently I can do:
```
try:
     intrinio_sdk.some_api_call()
except ApiException as e:
     if e.status == 429:
          # Wait some random amount of seconds then retry
     elif 400 <= e.status < 500:
          # Log error and exit
     elif 500 <= e.status < 600:
          # Log error and wait a set amount of second then retry
```
I'd like to be able to do:
```
try:
     intrinio_sdk.some_api_call()
except ThrottlingError as e:
     # Wait some random amount of seconds then retry
except ClientError as e:
     # Log error and exit
except ServerError as e:
     # Log error and wait a set amount of seconds then retry
```
As you can see, the bottom makes for much cleaner and readable code.

**Comment by kgmiller** [comment]
Thanks @RobRoseKnows - great idea! We will be improving error handling and documentation in upcoming releases.
