### ISSUE TITLE
'value': 'nm' causes uncaught ValueError exception

### ISSUE THREAD

**Issue by mchu1130** [intrinio/python-sdk#8]
cannot convert str to float in api_client.py:542.
you can replicate with this request from the web api:
https://api-v2.intrinio.com/historical_data/A/pricetobook?start_date=2008-01-01&end_date=2008-12-31

I was able to work around it by catching the ValueError and returning float('nan') once I found the blog post about what the 'nm' value means. Would be nice if it didn't crash though.

**Comment by kgmiller** [comment]
Thanks for the catch @mchu1130 and @paiforsyth - we'll have a fix for this issue in the next patch release of the SDK.

**Comment by kgmiller** [comment]
This issue has been resolved. Intrinio API v2 now returns null rather than "nm" when a data point value is not meaningful.
