### ISSUE TITLE
next_page parameter in get_economic_index_historical_data() not effective

### ISSUE THREAD

**Issue by oyassin** [intrinio/python-sdk#9]
When breaking up a call using ```get_economic_index_historical_data()``` under the ```IndexApi```, the ```next_page``` parameter seems to be ineffective. The new calls return the same exact data. I think this used to be an issue with other methods like ```get_all_economic_indices()``` as of a few days ago but got fixed with the latest version there (v2.0.0), but didn't seem to carry over in ```get_economic_index_historical_data()```.

Thanks

**Comment by kgmiller** [comment]
Much thanks for the heads-up on this one @oyassin - we have a PR out for a fix now, will be deployed this week ASAP. I'll close this issue out once deployed.

**Comment by oyassin** [comment]
Thanks @kgmiller, I appreciate it!

**Comment by kgmiller** [comment]
This issue has been resolved. Give it a shot now @oyassin 👍

**Comment by oyassin** [comment]
Thanks @kgmiller, worked like a charm! 👌
